baseurl = "/"
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
staticDir = ['static']
title = "Eduardo Méndez - Professional DevOps Engineer CV"

[languages]
   [languages.en]
        languageName = "EN"
        weight = 1
        title = "Eduardo Méndez - Professional DevOps Engineer CV"